server:
  port: 8092

spring:
  application:
    name: booking
  profiles:
    active: H2
# Общие свойства JPA
spring.jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true

# Настройки Liquibase
spring.liquibase.change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, loggers
    access:
      default:
  endpoint:
    health:
      access: unrestricted
    loggers:
      access: unrestricted
    prometheus:
      access: unrestricted
