spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookingservice
    driver-class-name: org.postgresql.Driver
    username: your_username
    password: your_password
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
