spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
  h2:
    console:
      enabled: true

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      id:
        new_generator_mappings: false
      hibernate: use-new-id-generator-mappings
